### ISSUE TITLE
[FEAT] 풀리퀘 머지 및 뷰 간 연결 작업

### ISSUE THREAD

**Issue by dayo2n** [GYURI-PARK/MC2_Morning_0404#41]
- [x] 풀리퀘 머지
- [x] 호제, 도리스랑 코드 확인

## TODO
- [x] 마이요망뷰에서 편집버튼 누르면 바로 이미지 피커 등장
- [x] 마크업뷰에서 완료 누르면 이미지 업로드
- [x] 오늘 내가 업로드해둔 이미지가 있으면 나갔다가 들어와도 마이요망뷰에 띄우기
- [x] YourYomangView에는 _일단 상대가 이미지 업데이트하면 뜨도록?ㄴㄴ_
   **백그라운드에 나갔다가 노티 이후 등장하도록! (== 백그라운드 태스크에서 한 번 데이터를 fetch해와서 UserDefaults에 값이 담기면 ㅇㅇ)**
- [x] connection flow부터 테스트
- [x] 노티
- [x] 위젯
- [x] 연결 완료되면 마이요망뷰로 넘어가기
- [x] 로그인 모달로 빠져
- [x] testflight 준비

## 머지 이후 TODO
- [x] 마이요망뷰 (isPressed, isHovering)에 대한 애니메이션 처리 (cc. @OreobrO )
- [x] 이미지랑 헨리의 애니메이션 연결 (이미지 업데이트하면 달 움직여)
- [x] 새벽 다섯시 데이터 fetch, 위젯 업데이트
- [x] backgroundTask에서 상대 이미지 데이터를 잘 불러오는지
- [x] 연결 이전에 "이곳을 눌러 상대방과 연결하세요" 어떻게 보일지?
    그리고 연결 이전에는 편집 버튼 아예 안뜨게 했는데 괜찮은지?
![Simulator Screen Recording - iPhone 14 Plus - 2023-05-16 at 01 56 43](https://github.com/GYURI-PARK/MC2_Morning_0404/assets/57654681/c76ffc37-0776-4913-ab89-872bd08fdbae)
