### ISSUE TITLE
[REFACTOR]

### ISSUE THREAD

**Issue by dayo2n** [GYURI-PARK/MC2_Morning_0404#49]
# TODO
- [ ] Color extension에 정의된 컬러를 사용
- [ ] 이미지 에셋이름, 시스템 이름 등 상수로 정의해 사용
- [ ] 커넥션 플로우 다시 고민하기 (코드 너무 길어요)
